QuanLyKho.Admin/Controllers/DatHangsController.cs
using Microsoft.AspNetCore.Mvc;
using QuanLyKho.ApiIntegration.ChiMucApiClient;
using QuanLyKho.ApiIntegration.DatHangApiClient;
using QuanLyKho.ViewModels.DatHang;
using QuanLyKho.WebAppAdmin.Controllers.Components;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QuanLyKho.Admin.Controllers
{
    public class DatHangsController : BaseController
    {
        private readonly IChiMucApiClient _chiMucApiClient;
        private readonly IDatHangApiClient _datHangApiClient;

        public DatHangsController(IChiMucApiClient chiMucApiClient, IDatHangApiClient datHangApiClient)
        {
            _chiMucApiClient = chiMucApiClient;
            _datHangApiClient = datHangApiClient;
        }

        public async Task<IActionResult> Index(string tuKhoa, string ngay, int pageIndex = 1, int pageSize = 10)
        {
            var chiMuc = await _chiMucApiClient.iNgayLamViec();
            if (!chiMuc.IsSuccessed)
            {
                return RedirectToAction("ChiMuc", "Home");
            }

            var bundle = new TimKiemPhieuNhapDaTra()
            {
                TuKhoa = tuKhoa,
                Ngay = ngay,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = await _datHangApiClient.GetAllPhieuNhapDaTra(bundle);
            ViewBag.ChiMuc = chiMuc.ResultObj;
            return View(data.ResultObj);
        }

        [HttpGet]
        public async Task<IActionResult> GetAllKeHoachDatHangChuaHoanThanh(TimKiemDatHang bundle)
        {
            var result = await _datHangApiClient.GetAllKeHoachDatHangChuaHoanThanh(bundle);
            return Ok(result);
        }

        [HttpGet]
        public async Task<IActionResult> GetTienDaThanhToan(long id)
        {
            var result = await _datHangApiClient.GetTienDaThanhToan(id);
            return Ok(result);
        }

        [HttpGet]
        public async Task<IActionResult> GetDanhSachDatHang(long id)
        {
            var result = await _datHangApiClient.GetDanhSachDatHang(id);
            return Ok(result);
        }

        [HttpGet]
        public async Task<IActionResult> NhaCungCapDatHang(string tuKhoa)
        {
            var result = await _datHangApiClient.NhaCungCapDatHang(tuKhoa);
            return Ok(result);
        }

        [HttpGet]
        public async Task<IActionResult> HuyChiTietDatHang(long id)
        {
            var result = await _datHangApiClient.HuyChiTietDatHang(id);
            return Ok(result);
        }

        [HttpGet]
        public async Task<IActionResult> UpdateThanhToan(long id, string tienDaTra)
        {
            var result = await _datHangApiClient.UpdateThanhToan(id, tienDaTra);
            return Ok(result);
        }

        [HttpGet]
        public async Task<IActionResult> GetChiTietPhieuNhap(long id)
        {
            var result = await _datHangApiClient.GetChiTietPhieuNhap(id);
            return Ok(result);
        }

        [HttpGet]
        public async Task<IActionResult> GetAllPhieuNhapChuaTra(TimKiemDatHang bundle)
        {
            var result = await _datHangApiClient.GetAllPhieuNhapChuaTra(bundle);
            return Ok(result);
        }

        [HttpPost]
        public async Task<IActionResult> Create(NhapHoaDon bundle)
        {
            var result = await _datHangApiClient.Create(bundle);
            return Ok(result);
        }
    }
}

QuanLyKho.Admin/Controllers/QuanLyMaSosController.cs
using Microsoft.AspNetCore.Mvc;
using QuanLyKho.ApiIntegration.QuanLyMaSoApiClient;
using QuanLyKho.Data.Extensions.Enums;
using QuanLyKho.ViewModels.QuanLyMaSo;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QuanLyKho.Admin.Controllers
{
    public class QuanLyMaSosController : Controller
    {
        private readonly IQuanLyMaSoApiClient _quanLyMaSoApiClient;

        public QuanLyMaSosController(IQuanLyMaSoApiClient quanLyMaSoApiClient)
        {
            _quanLyMaSoApiClient = quanLyMaSoApiClient;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetAll(MaLoai type)
        {
            var result = await _quanLyMaSoApiClient.GetAll(type);
            return Ok(result);
        }

        [HttpGet]
        public async Task<bool> iTen(string ten, int? id)
        {
            var data = await _quanLyMaSoApiClient.iTen(ten, id);
            return data.IsSuccessed;
        }

        [HttpPost]
        public async Task<IActionResult> Create(TaoMaSo bundle)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            var result = await _quanLyMaSoApiClient.Create(bundle);

            return Ok(result);
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var result = await _quanLyMaSoApiClient.Delete(id);
            return Ok(result);
        }

        [HttpPut]
        public async Task<IActionResult> Update(CapNhatMaSo bundle)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            var result = await _quanLyMaSoApiClient.Update(bundle);
            return Ok(result);
        }
    }
}

QuanLyKho.Admin/Views/DatHangs/DanhSachDatHang.cshtml
<section class="content">
    <!-- Default box -->
    <div class="card collapsed-box">
        <div class="card-header">
            <h3 class="card-title">Danh Sách Kế Hoạch Đang Chờ Nhập Hóa Đơn</h3>

            <div class="card-tools">
                <span title="Kế Hoạch Đặt Hàng" data-toggle="tooltip" data-placement="top" class="badge badge-warning" id="SoHDCTT" style="float:left;">
                </span>
                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                    <i class="fas fa-plus"></i>
                </button>
            </div>
        </div>
        <div class="card-body" style="display: none;">

            <form id="frmTKKH" method="get">
                <div class="row">
                    <div class="col-md-10 offset-md-1">
                        <div class="row">
                            <div class="col-4">
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="text" class="form-control" id="NgayTKKH" name="ngayDuKien" placeholder="Chọn ngày dự kiến">
                                        <div class="input-group-append">
                                            <button type="button" onclick="resetLaiNgayTKKH()" class="btn btn-default" title="Không tìm kiếm theo ngày">
                                                <i class="fa fa-refresh"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-8">
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="search" class="form-control" name="tuKhoa" id="tuKhoaTKKH"
                                               placeholder="Nhập mã số hoặc tên kế hoạch">
                                        <div class="input-group-append">
                                            <button type="submit" class="btn btn-default" title="Tìm kiếm kế hoạch chế biến">
                                                <i class="fa fa-search"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            <table id="example25656" class="table table-bordered table-striped table-hover">
                <thead>
                    <tr>
                        <th>Mã Số</th>
                        <th>Tên</th>
                        <th>Ngày Tạo</th>
                        <th>Người Tạo</th>
                        <th>Người Nhận</th>
                        <th>Trạng Thái</th>
                        <th class="text-center">Thao Tác</th>
                    </tr>
                </thead>
                <tbody id="phanPhoiTableShow">
                    <tr class="delete-kehoach text-center">
                        <td colspan="7">Không tìm thấy dữ liệu</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <!-- /.card-body -->
    <!-- /.card -->
</section>
<!-- xem hóa đơn -->
<!--Modal-->
<div class="modal fade bd-example-modal-lg" id="modalXem" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Xem Phiếu Chế Biến</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <!---->
            <div class="modal-body">
                <div class="form-row">
                    <input type="hidden" id="idKeHoachXem" />
                    <div class="form-group col-md-6">
                        <label>Mã Lưu Trữ:</label>
                        <span class="form-control" id="maLuuTruDH" style="border:none; border-bottom:1px solid #EEEEEE;">
                        </span>
                    </div>
                    <div class="form-group col-md-6">
                        <label>Mã Kế Hoạch:</label>
                        <span class="form-control" id="maKHDH" style="border:none; border-bottom:1px solid #EEEEEE;">
                        </span>
                    </div>
                </div>
                <div class="form-row">
                    <input type="hidden" id="idKeHoachXem" />
                    <div class="form-group col-md-6">
                        <label>Số Hóa Đơn:</label>
                        <span class="form-control" id="soHoaDonDH" style="border:none; border-bottom:1px solid #EEEEEE;">
                        </span>
                    </div>
                    <div class="form-group col-md-6">
                        <label>Người Tạo:</label>
                        <span class="form-control" id="nguoiTaoDH" style="border:none; border-bottom:1px solid #EEEEEE;">
                        </span>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label>Ngày Tạo:</label>
                        <span class="form-control" id="ngayTaoDH" style="border:none; border-bottom:1px solid #EEEEEE;">
                        </span>
                    </div>
                    <div class="form-group col-md-6">
                        <label>Ngày Mua:</label>
                        <span class="form-control" id="ngayMuaDH" style="border:none; border-bottom:1px solid #EEEEEE;">
                        </span>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label>Trạng Thái:</label>
                        <span class="form-control" id="trangThaiDH" style="border:none; border-bottom:1px solid #EEEEEE;">
                        </span>
                    </div>
                    <div class="form-group col-md-6">
                        <label>Nhà Cung Cấp:</label>
                        <span class="form-control" id="nhaCungCapDH" style="border:none; border-bottom:1px solid #EEEEEE;">
                        </span>
                    </div>
                </div>
                <div class="card-body">
                    <label>
                        Danh Sách Đặt Hàng
                    </label>
                    <table id="tableShowViewKH12" class="table table-bordered table-striped table-hover table-responsive-xl">
                        <thead>
                            <tr>
                                <th>Mã Số</th>
                                <th>Tên Nguyên Vật Liệu</th>
                                <th>ĐVT</th>
                                <th>Số Lượng</th>
                                <th>Đơn Giá</th>
                                <th>Giảm Giá</th>
                                <th>Thành Tiền</th>
                            </tr>
                        </thead>
                        <tbody id="ShowViewKH12DH">
                        </tbody>
                    </table>
                    <label style="float:right; margin-top: 20px;" id="TongTien"></label>
                </div>
            </div>
            <!---->
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
            </div>
        </div>
    </div>
</div>
<!--Modal xem danh sách đặt hàng-->
<div class="modal fade bd-example-modal-lg" id="HuyKeHoachDatHang" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Xem Danh Sách Đặt Hàng</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <!---->
            <div class="modal-body">
                <div class="card-body">
                    <label>
                        Danh Sách Đặt Hàng
                    </label>
                    <table id="tableShowViewKH12" class="table table-bordered table-striped table-hover table-responsive-xl">
                        <thead>
                            <tr>
                                <th>Mã Số</th>
                                <th>Nguyên Vật Liệu</th>
                                <th>Số Lượng</th>
                                <th>Số Lượng Đã Thêm</th>
                                <th>ĐVT</th>
                                <th class="text-center">Thao Tác</th>
                            </tr>
                        </thead>
                        <tbody id="ShowViewHuyKeHoachDatHang">
                        </tbody>
                    </table>
                    <label style="float:right; margin-top: 20px;" id="TongTien"></label>
                </div>
            </div>
            <!---->
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
            </div>
        </div>
    </div>
</div>
<!--Modal hủy phiếu -->
<div class="modal fade" id="modalHoiHuyDatHang" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Hủy Phiếu Đặt Hàng</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <!---->
            <div class="modal-body">
                <input type="hidden" id="idHoiHuyDatHang" />
                <input type="hidden" id="idKeHoachDHHuy" />

                <h5 class="modal-title">
                    Bạn có muốn hủy chi tiết đặt hàng này không ?
                </h5>
            </div>
            <!---->
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
                <button type="submit" onclick="ajaxHuyDatHang()" class="btn btn-primary">Đồng Ý</button>
            </div>
        </div>
    </div>
</div>

QuanLyKho.Admin/Views/DatHangs/NhapHoaDon.cshtml
@using QuanLyKho.Data.Extensions.Enums;
<style>
    #modalThem {
        overflow-y: scroll
    }
</style>

<!--Modal Nhập hàng-->
<div class="modal fade  bd-example-modal-lg" id="modalThem" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Nhập Hóa Đơn</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <!---->
            <form id="CreateHoaDonBill" method="post">

                <div class="modal-body">
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>Mã Lưu Trữ</label>
                            <select id="CodeChon" name="MaLuuTru" class="form-control" required>
                            </select>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="inputEmail4">Số Hóa Đơn</label>
                            <input type="text" class="form-control" name="SoHoaDon" id="SoHoaDon" onkeyup="checkSHD()" placeholder="Số hóa đơn" required>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>Nhà Cung Cấp</label>
                            <button type="button" class="form-control" onclick="GetNhaCungCap()"
                                    data-toggle="modal" data-target="#exampleNhaCungCap">
                                <div id="NameNhaCungCap"></div>
                            </button>
                            <input id="IdSupliers" name="IdNhaCungCap" type="hidden" />
                        </div>
                        <div class="form-group col-md-6">
                            <label for="inputEmail4">Ngày Mua Hàng</label>
                            <input type="date" class="form-control" name="NgayMua" required>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>Thuế Suất GTGT (%)</label>
                            <input type="text" class="form-control" onkeyup="checkThue()" id="Thue" name="SoThue" placeholder="Thuế suất GTGT">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="inputEmail4">Số Tiền Đã Thanh Toán (VNĐ)</label>
                            <input type="text" class="form-control" id="AmountPaidShow" onkeyup="checkAmoutPaid()" value="0" placeholder="Số tiền đã thanh toán" required>
                            <input type="hidden" class="form-control" name="SoTienDaThanhToan" id="AmountPaid" value="0" required>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <h5>Danh Sách Nguyên Vật Liệu</h5>
                        </div>
                        <input type="hidden" class="form-control" name="IdChiMuc" value="@ViewBag.ChiMuc">
                        <input name="NguoiTao" type="hidden" value="@User.Identity.Name" />
                        <input id="IdOrderPlan" name="IdKeHoach" type="hidden" />
                        <input class="form-control" type="hidden" value="0" name="TongTien" id="tongTienHoaDon" />
                        <table id="table34NCC" class="table table-bordered table-striped table-hover table-responsive-xl">
                            <thead>
                                <tr>
                                    <th>Mã Số</th>
                                    <th>Tên</th>
                                    <th>ĐVT</th>
                                    <th>Số Lượng</th>
                                    <th>Đơn Giá (VNĐ)</th>
                                    <th>Giảm Giá (%)</th>
                                    <th>Thành Tiền (VNĐ)</th>
                                </tr>
                            </thead>
                            <tbody id="tableAddNVL">
                                <tr>
                                    <td>hihi</td>
                                    <td></td>
                                    <td></td>
                                    <td>
                                        <input class="form-control" type="number" min="0" max="0" value="0" name="SoLuong[]" />
                                    </td>
                                    <td>
                                        <input class="form-control" type="number" min="0" max="0" value="0" name="DonGia[]" />
                                    </td>
                                    <td>
                                        <input class="form-control" type="number" min="0" max="100" value="0" name="GiamGia[]" />
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
                    <button type="submit" class="btn btn-primary">Lưu Lại</button>
                </div>
            </form>

            <!---->
        </div>
    </div>
</div>

<!--Modal nhà cung cấp-->
<div class="modal fade  bd-example-modal-lg" id="exampleNhaCungCap" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Nhà Cung Cấp</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <!---->
            <div class="modal-body">
                <form id="frmTKNCCBill" method="post">
                    <div class="form-group">
                        <input class="form-control" type="search" style="width:93%; float:left; margin-right:7px;" id="keywordNCC"
                               placeholder="Tìm kiếm mã số hoặc tên nhà cung cấp" aria-label="Search" required>
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit">
                                <i class="fas fa-search fa-fw"></i>
                            </button>
                        </div>
                    </div>
                </form>
                <div class="row">
                    <div class="col-12">
                        <h5>Danh Sách Tìm Kiếm</h5>
                    </div>
                    <table id="table34NCCBill" class="table table-bordered table-striped table-hover">
                        <thead>
                            <tr>
                                <th>Mã Số</th>
                                <th>Tên</th>
                                <th>Địa Chỉ</th>
                                <th class="text-center">Thêm</th>
                            </tr>
                        </thead>
                        <tbody id="tableAddNCCBill">
                        </tbody>
                    </table>
                </div>
            </div>
            <!---->
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
            </div>
        </div>
    </div>
</div>
<script>
    // lấy mã code lưu trữ
    GetCodeNhapDatHang();
    // Lấy giá trị của mã User
    function GetCodeNhapDatHang() {
        var typeMVL = "@MaLoai.HoaDon";
         $.ajax({
             type: "GET",
              url: "@Url.Action("GetAll","QuanLyMaSos")",
             data: {type: typeMVL} ,
             dataType: "json",
            success: function (msg) {
                msg.forEach(function (item) {
                    //Code
                    str = '<option value="' + item.ten +'">'+item.ten+'</option>';
                    $('#CodeChon').append(str);
                });

                },
                error: function (req, status, error) {

                }
            });
    }

    // nhập hóa đơn
    var CreateHoaDonBill = $("#CreateHoaDonBill");
    CreateHoaDonBill.submit(function (e) {
        var idSuppliers = $("#IdSupliers").val();
        if (idSuppliers <= 0) {
            toastr.error('Vui lòng chọn nhà cung cấp');
        } else {
            var thue = $("#Thue").val();

            if (thue < 0 || thue > 100) {
                toastr.error('Vui lòng nhập thuế trong khoảng từ 0 - 100');
            } else {
              $.ajax({
             type: "POST",
              url: "@Url.Action("Create")",
              data: CreateHoaDonBill.serialize() ,
             dataType: "json",
            success: function (msg) {
                if (msg.isSuccessed) {
                    toastr.success('Tạo thành công');
                    $("#modalThem").modal("hide");
                    $("#CreateHoaDonBill").trigger("reset");
                    if (msg.resultObj.trangThai == "Đã thanh toán") {
                        var str = ' <tr '+ msg.resultObj.id + '">'
                            + ' <td>' + msg.resultObj.maLuuTru + '</td>'
                            + ' <td>' + msg.resultObj.maKeHoach + '</td>'
                            + ' <td>' + msg.resultObj.ngayTao + '</td>'
                            + ' <td>' + msg.resultObj.nguoiTao + '</td>'
                            + ' <td>' + msg.resultObj.trangThai + '</td>'
                            + '  <td class="text-center">'
                            + '<div class="btn-group btn-group-sm">'
                            + '<a class="btn btn-success" data-toggle="modal" data-target="#modalXem"'
                            + 'onclick = "XemHoaDon(' + msg.resultObj.id + ')" title = "Xem phiếu nhập hóa đơn">'
                            + ' <i class="fas fa-eye"></i>'
                            + '           </a>'
                                + '     </div>'
                            + '    </td>'
                            + ' </tr >';

                        $("#XemThongTinPCBTB1").prepend(str);

                        var text = document.getElementById("SoHDCTT").innerText;
                        var soLuong = text - 1;
                        document.getElementById("SoHDCTT").innerHTML = soLuong;
                    }
                    else {
                        DatHangChuaTraTien(" ", " ");
                    }

                    if (msg.resultObj.trangThaiHoanKH == "1") {
                        var xoa = "#keHoachDE-" + msg.resultObj.idKeHoach;
                        $(xoa).remove();
                    }

                    msg.resultObj.nhacNhoSoLuongs.forEach(function (item) {
                        // gửi thông điệp
                        var user = item.nguoiNhan;
                        var message =
                        {
                            Id: item.idThongBao,
                            Ten: item.ten,
                            DuongDan: item.duongDan,
                        };
                        connectionNhacNho.invoke("SendNhacNho", user, message).catch(function (err) {
                            return console.error(err.toString());
                        });
                    });

                } else {
                    toastr.error(msg.message);

                }

                },
                error: function (req, status, error) {
                    toastr.error('Tạo thất bại');
                }
            });

            }
        }

        e.preventDefault();
    });
</script>